#!/bin/bash

set -euo pipefail

COMMON_SH="/home/steges/agent/skills/skill-forge/scripts/common.sh"
# shellcheck source=/dev/null
source "$COMMON_SH"

SM_ROOT="${AUTHORING_SM_ROOT:-$SM_ROOT}"
STATE_DIR="${AUTHORING_STATE_DIR:-$STATE_DIR}"
POLICY_DIR="${AUTHORING_POLICY_DIR:-$POLICY_DIR}"
AUDIT_LOG="${AUTHORING_AUDIT_LOG:-$AUDIT_LOG}"
AUTHORING_SKILLS_ROOT="${AUTHORING_SKILLS_ROOT:-/home/steges/agent/skills}"
AUTHORING_QUEUE_PATH="$STATE_DIR/author-queue.json"
AUTHORING_KNOWN_SKILLS_PATH="$STATE_DIR/known-skills.json"

usage() {
  echo "Usage: authoring-dispatch.sh <name> [--mode auto|template|from-tested|scratch] [--reason <text>]"
}

normalize_slug() {
  python3 - "$1" <<'PY'
import re
import sys

raw = sys.argv[1].strip().lower()
slug = re.sub(r'[^a-z0-9]+', '-', raw).strip('-')
slug = re.sub(r'-{2,}', '-', slug)
print(slug)
PY
}

mode_quality_meta() {
  case "$1" in
    template)
      echo "90|high|generated from template scaffolding"
      ;;
    from-tested)
      echo "80|medium-high|generated with tested-skill context available"
      ;;
    scratch)
      echo "60|medium|generated from generic scratch scaffolding"
      ;;
    *)
      echo "50|low|unknown mode"
      ;;
  esac
}

detect_mode_auto() {
  local reason="$1"
  if [[ "$reason" =~ (template|vorlage|runbook|ops) ]]; then
    echo "template"
    return
  fi
  if [[ -f "$SM_ROOT/catalog/tested-skills.json" ]]; then
    echo "from-tested"
    return
  fi
  echo "scratch"
}

check_duplicate_slug() {
  local slug="$1"
  python3 - "$slug" "$AUTHORING_KNOWN_SKILLS_PATH" "$AUTHORING_SKILLS_ROOT" <<'PY'
import json
import os
import re
import sys

slug, known_path, skills_root = sys.argv[1:4]

def normalize(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r'[^a-z0-9]+', '-', value).strip('-')
    value = re.sub(r'-{2,}', '-', value)
    return value

try:
    with open(known_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
except Exception:
    data = {}

for key, row in data.items():
    existing = str(row.get('slug', key))
    if normalize(existing) == slug or normalize(key) == slug:
        print(f"known-skills:{existing}")
        raise SystemExit(1)

if os.path.isdir(skills_root):
    for entry in os.listdir(skills_root):
        path = os.path.join(skills_root, entry)
        if os.path.isdir(path) and normalize(entry) == slug:
            print(f"skill-dir:{entry}")
            raise SystemExit(1)

print("OK")
PY
}

enqueue_job() {
  local requested_name="$1"
  local slug="$2"
  local mode="$3"
  local reason="$4"
  local quality_score="$5"
  local quality_tier="$6"

  python3 - "$requested_name" "$slug" "$mode" "$reason" "$quality_score" "$quality_tier" "$AUTHORING_QUEUE_PATH" <<'PY'
import json
import sys
from datetime import datetime, timezone

sys.path.insert(0, '/home/steges/agent/skills/skill-forge/scripts')
from py_helpers import write_json_atomic

requested_name, slug, mode, reason, quality_score, quality_tier, path = sys.argv[1:8]

with open(path, 'r', encoding='utf-8') as f:
    rows = json.load(f)

job_id = f"author-{int(datetime.now(timezone.utc).timestamp())}-{abs(hash((slug, mode, reason, datetime.now(timezone.utc).isoformat()))) % 10000}"
rows.append({
    'id': job_id,
    'name': requested_name,
    'slug': slug,
    'mode': mode,
    'reason': reason,
    'quality_score': int(quality_score),
    'quality_tier': quality_tier,
    'status': 'queued',
    'created_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
})
write_json_atomic(path, rows)
print(job_id)
PY
}

create_skill_files() {
  local requested_name="$1"
  local slug="$2"
  local mode="$3"
  local reason="$4"
  local quality_score="$5"
  local quality_tier="$6"
  local quality_note="$7"

  local skill_dir="$AUTHORING_SKILLS_ROOT/$slug"
  mkdir -p "$skill_dir/agents" "$skill_dir/scripts" "$skill_dir/contracts" "$skill_dir/references"

  local description="Generated by skill-forge authoring engine ($mode)"
  local purpose="Provide capability: $reason"
  local trigger="When user asks for '$requested_name' workflows or matching tasks."

  if [[ -f "$SM_ROOT/templates/skill/SKILL.template.md" ]]; then
    sed \
      -e "s/{{NAME}}/$slug/g" \
      -e "s/{{DESCRIPTION}}/$description/g" \
      -e "s/{{PURPOSE}}/$purpose/g" \
      -e "s/{{TRIGGER}}/$trigger/g" \
      "$SM_ROOT/templates/skill/SKILL.template.md" > "$skill_dir/SKILL.md"
  else
    cat > "$skill_dir/SKILL.md" <<EOF
---
name: $slug
description: $description
---

# $slug

## Purpose
$purpose

## Trigger
$trigger
EOF
  fi

  cat > "$skill_dir/references/AUTHORING.md" <<EOF
# Authoring Report

- requested_name: $requested_name
- slug: $slug
- mode: $mode
- quality_score: $quality_score
- quality_tier: $quality_tier
- quality_note: $quality_note
- reason: $reason
- created_at: $(now_iso)
- created_by: skill-forge
EOF

  cat > "$skill_dir/contracts/default.output.schema.json" <<EOF
{
  "\$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "${slug} default output",
  "type": "object",
  "required": ["status", "summary"],
  "properties": {
    "status": {
      "type": "string",
      "enum": ["ok", "needs-input", "blocked", "error"]
    },
    "summary": {
      "type": "string",
      "minLength": 1
    },
    "details": {
      "type": ["string", "array", "object"]
    }
  },
  "additionalProperties": true
}
EOF

  cat > "$skill_dir/scripts/${slug}-dispatch.sh" <<EOF
#!/bin/bash
set -euo pipefail

usage() {
  echo "Usage: ${slug}-dispatch.sh <subcommand> [args]"
}

subcommand="\${1:-}"
case "\$subcommand" in
  "")
    usage
    exit 2
    ;;
  *)
    echo "Draft skill '${slug}' is scaffolded but not implemented yet: \$subcommand" >&2
    exit 2
    ;;
esac
EOF

  python3 - "$skill_dir/scripts/${slug}-dispatch.sh" <<'PY'
import os
import stat
import sys

path = sys.argv[1]
mode = os.stat(path).st_mode
os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
PY
}

update_known_skill() {
  local requested_name="$1"
  local slug="$2"
  local mode="$3"
  local quality_score="$4"
  local quality_tier="$5"

  python3 - "$requested_name" "$slug" "$mode" "$quality_score" "$quality_tier" "$AUTHORING_KNOWN_SKILLS_PATH" <<'PY'
import json
import sys
from datetime import datetime, timezone

sys.path.insert(0, '/home/steges/agent/skills/skill-forge/scripts')
from py_helpers import write_json_atomic

requested_name, slug, mode, quality_score, quality_tier, path = sys.argv[1:7]

with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

row = data.get(slug, {'slug': slug, 'source': 'author-engine', 'version': '0.1.0'})
row['display_name'] = requested_name
row['status'] = 'drafted'
row['authoring_mode'] = mode
row['authoring_quality_score'] = int(quality_score)
row['authoring_quality_tier'] = quality_tier
row['drafted_at'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
data[slug] = row
write_json_atomic(path, data)
PY
}

main() {
  ensure_dirs
  init_state_files

  [[ $# -ge 1 ]] || { usage; exit 1; }
  local requested_name="$1"
  shift

  local mode="auto"
  local reason="requested by user"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode)
        mode="${2:-}"
        shift 2
        ;;
      --reason)
        reason="${2:-}"
        shift 2
        ;;
      *)
        echo "Unknown arg: $1"
        usage
        exit 1
        ;;
    esac
  done

  if [[ "$mode" == "auto" ]]; then
    mode="$(detect_mode_auto "$reason")"
  fi

  case "$mode" in
    template|from-tested|scratch) ;;
    *)
      echo "Invalid mode: $mode"
      exit 1
      ;;
  esac

  local slug
  slug="$(normalize_slug "$requested_name")"
  [[ -n "$slug" ]] || {
    echo "ERROR: Could not derive a valid slug from name: $requested_name" >&2
    exit 1
  }

  if [[ "$(is_incident_freeze_on)" == "1" ]]; then
    echo "Incident freeze active: authoring allowed as draft only."
  fi

  local dup_origin
  if dup_origin="$(check_duplicate_slug "$slug")"; then
    :
  else
    echo "ERROR: Normalized slug collision for '$requested_name' -> '$slug' ($dup_origin)." >&2
    echo "  Use a different name or update the existing skill." >&2
    exit 1
  fi

  local quality_meta quality_score quality_tier quality_note
  quality_meta="$(mode_quality_meta "$mode")"
  IFS='|' read -r quality_score quality_tier quality_note <<< "$quality_meta"

  local id
  id="$(with_state_lock enqueue_job "$requested_name" "$slug" "$mode" "$reason" "$quality_score" "$quality_tier")"
  with_state_lock create_skill_files "$requested_name" "$slug" "$mode" "$reason" "$quality_score" "$quality_tier" "$quality_note"
  with_state_lock update_known_skill "$requested_name" "$slug" "$mode" "$quality_score" "$quality_tier"
  log_audit "AUTHOR" "$slug" "job=$id mode=$mode quality=$quality_tier requested_name=$requested_name drafted"

  if [[ "$requested_name" == "$slug" ]]; then
    echo "Authored draft skill: $slug (mode=$mode, quality=$quality_tier/$quality_score, job=$id)"
  else
    echo "Authored draft skill: $requested_name -> $slug (mode=$mode, quality=$quality_tier/$quality_score, job=$id)"
  fi
}

main "$@"
